image: python:3.5.1
pipelines:
  default:
    - step:
        script:
          - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
          - python get-pip.py
          - pip install pylint
          - pip install coverage
          - cd kode
          - bash pipelinelint.bash
          - coverage run --source=. -m unittest && coverage report