image: python:3.5.1
pipelines:
  default:
    - step:
        script:
          - apt-get clean
          - rm -rf /var/lib/apt/lists/*
          - apt-get clean
          - apt-get update 
          - apt-get upgrade
          - apt-get install bc
          - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
          - python get-pip.py
          - pip install pylint
          - pip install coverage
          - bash pipelinelint.bash
          - coverage run --source=. -m unittest discover kode && coverage report